position_setpoints:
  - [0.0, 0.0, -2.25] # Takeoff gradually 
  - [0.0, 0.0, -3.0] # Goto -3.0 over landing
  - [3.0, 0.0, -3.0] # go to #1
  - [3.0, 0.0, -3.0, -6.28] # yaw leftward 360
  - [3.0, 0.0, -3.0, 6.28] # yaw rightward 360
  - [3.0, 0.0, -3.75] # Climb Gradually 
  - [3.0, 0.0, -4.5] # Climb to 4.5 m
  - [3.0, 0.0, -3.75] # Descend Gradually
  - [3.0, 0.0, -3.0] # Descend to 3.0 and Stand over #1
  - [6.0, 0.0, -3.0] # Pitch foward to #2 
  - [3.0, 0.0, -3.0] # Pitch backward to #1
  - [6.0, 0.0, -3.0] # Pitch foward to #2
  - [6.0, 0.0, -3.0, -3.14] # Yaw left 180 over #2
  - [0.0, 0.0, -3.0] # Pitch backward to landing
  - [0.0, 0.0, -3.0, 3.14] # Yaw right 180

traverse_leftward:

  - [0.0, 0.0, -2.25]
  - [0.0, 0.0, -3.0]
  - [3.0, 3.0, -3.0]
  - [6.0, 3.0, -3.0]
  - [9.0, 3.0, -3.0]
  - [12.0, 0.0, -3.0]
  - [9.0, -3.0, -3.0]
  - [6.0, -3.0, -3.0]
  - [3.0, -3.0, -3.0]
  - [0.0, 0.0, -3.0]

traverse_rightward:

  - [0.0, 0.0, -2.25]
  - [0.0, 0.0, -3.0]
  - [3.0, -3.0, -3.0]
  - [6.0, -3.0, -3.0]
  - [9.0, -3.0, -3.0]
  - [12.0, 0.0, -3.0]
  - [9.0, 3.0, -3.0]
  - [6.0, 3.0, -3.0]
  - [3.0, 3.0, -3.0]
  - [0.0, 0.0, -3.0]